version: '3.8'

services:
  authusers.webapi:
    image: ${DOCKER_REGISTRY-}authuserswebapi
    build:
      context: .
      dockerfile: AuthUsers.WebApi/Dockerfile
    depends_on:
      - postgres-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=authdb;Username=authuser;Password=Teste123

  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: Teste123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
